### ISSUE TITLE
Infinitely nested inputs 

### ISSUE THREAD

**Issue by mikesteele** [Tombarr/html-resume-template#1]
Pressing "enter" in an input without adding a value will infinitely nest inputs, breaking the layout of the page.

<img width="950" alt="screen shot 2018-07-06 at 12 58 35 pm" src="https://user-images.githubusercontent.com/3904909/42391161-78c4dcc2-811c-11e8-84b4-8d3ef0b2770d.png">

**Comment by mikesteele** [comment]
Also possible to nest inputs in one field:
<img width="349" alt="screen shot 2018-07-06 at 1 10 23 pm" src="https://user-images.githubusercontent.com/3904909/42391618-f7082e76-811d-11e8-8b62-e67e60b60e43.png">

**Comment by Tombarr** [comment]
Seems to be related to styles strangely enough. Here's a few screencasts:
@mikesteele Please take a look at the latest commit to confirm that the issue is resolved.

`display: inline-block`

<img src="http://g.recordit.co/gEJVSZLCLW.gif" />

`display: block`

<img src="http://g.recordit.co/QojvFgUNSa.gif" />

`display: block; float: left;`

<img src="http://g.recordit.co/RMid0aT1ME.gif" />
